# SPDX-License-Identifier: GPL-2.0-only
# Builds one image containing both ucrs-server and ucrs-decoder;
# docker-compose runs them as separate services sharing a data volume.

FROM docker.io/library/rust:1-bookworm AS build
WORKDIR /src
COPY Cargo.toml Cargo.lock ./
COPY crates crates
COPY migrations migrations
RUN cargo build --release -p ucrs-server -p ucrs-decoder

FROM docker.io/library/debian:bookworm-slim
RUN apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates && \
    rm -rf /var/lib/apt/lists/*
COPY --from=build /src/target/release/ucrs-server \
                  /src/target/release/ucrs-decoder /usr/local/bin/
RUN useradd -r -u 900 -d /data ucrs
USER ucrs
CMD ["ucrs-server", "/config/config.toml"]
